ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'WAITING_PICKUP';
ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'PICKED_UP';
ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'IN_TRANSIT';
ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'RETURNED';
ALTER TYPE "ShippingStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TABLE "Order" ADD COLUMN "carrierName" TEXT NOT NULL DEFAULT '', ADD COLUMN "trackingCode" TEXT NOT NULL DEFAULT '';
