import { useState } from 'react';
import { Plus, Phone, MessageCircle, Home, Pencil, Trash } from 'lucide-react';
import { api } from '../api';
import { Actor, Page, date } from './types';
import { useResource, State, Modal, Form, Pager, SearchBox } from './shared';

export type Task = {
  id: string;
  title: string;
  note: string;
  dueDate: string | null;
  priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  status: 'TODO' | 'IN_PROGRESS' | 'DONE' | 'CANCELLED';
  contactChannel: string;
  completedAt: string | null;
  autoGenerated: boolean;
  createdAt: string;
  version: number;
  customer?: { id: string; name: string } | null;
  user?: { id: string; displayName: string };
};

export function MyTasks({ actor }: { actor: Actor }) {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [revision, setRevision] = useState(0);
  const [modal, setModal] = useState<'create' | Task | null>(null);

  const result = useResource<Page<Task>>(
    '/sales/tasks?page=' + page + '&pageSize=20' + 
    (status ? '&status=' + status : '') + 
    (search ? '&search=' + encodeURIComponent(search) : ''),
    revision
  );

  const toggleTask = async (task: Task) => {
    await api('/sales/tasks/' + task.id, 'PATCH', {
      version: task.version,
      status: task.status === 'DONE' ? 'TODO' : 'DONE'
    });
    setRevision(r => r + 1);
  };

  const deleteTask = async (task: Task) => {
    if (!confirm('Bạn có chắc chắn muốn xóa công việc này?')) return;
    await api('/sales/tasks/' + task.id, 'DELETE');
    setRevision(r => r + 1);
  };

  const todayStr = new Date().toISOString().slice(0, 10);

  return (
    <>
      <div className="page-head">
        <div>
          <h2>Công việc của tôi</h2>
        </div>
        <button className="primary" onClick={() => setModal('create')}>
          <Plus size={18} /> Tạo mới
        </button>
      </div>
      
      <div className="sales-toolbar">
        <SearchBox placeholder="Tìm công việc…" onSearch={s => { setSearch(s); setPage(1); }} />
        <label className="filter-label">
          Trạng thái
          <select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}>
            <option value="">Tất cả</option>
            <option value="TODO">Cần làm</option>
            <option value="IN_PROGRESS">Đang làm</option>
            <option value="DONE">Hoàn thành</option>
            <option value="CANCELLED">Đã hủy</option>
          </select>
        </label>
      </div>

      <State loading={result.loading} error={result.error} />
      {result.data && (
        <section className="panel">
          <div className="task-list" style={{ padding: 24 }}>
            {result.data.items.map(t => {
              const isOverdue = t.dueDate && t.dueDate < todayStr && t.status !== 'DONE';
              const isToday = t.dueDate === todayStr && t.status !== 'DONE';
              return (
                <div className="task-item" key={t.id}>
                  <input type="checkbox" checked={t.status === 'DONE'} onChange={() => toggleTask(t)} />
                  <span className={`priority-dot --${t.priority.toLowerCase()}`} />
                  <div style={{ flex: 1, textDecoration: t.status === 'DONE' ? 'line-through' : 'none' }}>
                    <strong>{t.title}</strong>
                    {t.customer && <span className="badge">{t.customer.name}</span>}
                    {t.dueDate && (
                      <small className={`block ${isOverdue ? 'overdue' : ''}`} style={{ color: isToday ? '#d97706' : undefined }}>
                        Hạn: {date(t.dueDate)}
                      </small>
                    )}
                  </div>
                  {t.contactChannel === 'phone' && <Phone size={16} />}
                  {t.contactChannel === 'zalo' && <MessageCircle size={16} />}
                  {t.contactChannel === 'visit' && <Home size={16} />}
                  
                  <div className="row-actions" style={{ marginLeft: 12 }}>
                    <button className="icon-button" onClick={() => setModal(t)}><Pencil size={16} /></button>
                    <button className="icon-button" onClick={() => deleteTask(t)}><Trash size={16} /></button>
                  </div>
                </div>
              );
            })}
          </div>
          <State loading={false} error="" empty={!result.data.items.length} />
          <Pager data={result.data} page={page} setPage={setPage} />
        </section>
      )}

      {modal && (
        <TaskModal 
          task={modal === 'create' ? null : modal} 
          close={() => setModal(null)} 
          done={() => { setModal(null); setRevision(r => r + 1); }} 
        />
      )}
    </>
  );
}

function TaskModal({ task, close, done }: { task: Task | null, close: () => void, done: () => void }) {
  const [search, setSearch] = useState('');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const customers = useResource<Page<any>>('/sales/customers?pageSize=20&search=' + encodeURIComponent(search));
  
  return (
    <Modal title={task ? 'Sửa công việc' : 'Thêm công việc'} close={close}>
      <Form
        label="Lưu"
        done={done}
        submit={async f => {
          const body = {
            title: f.get('title'),
            note: f.get('note'),
            customerId: f.get('customerId') || null,
            dueDate: f.get('dueDate') || null,
            priority: f.get('priority'),
            contactChannel: f.get('contactChannel'),
            ...(task ? { version: task.version, status: f.get('status') } : {})
          };
          await api('/sales/tasks' + (task ? '/' + task.id : ''), task ? 'PATCH' : 'POST', body);
        }}
      >
        <label>
          Tiêu đề
          <input name="title" required defaultValue={task?.title} maxLength={200} />
        </label>
        <label>
          Khách hàng
          <input type="text" placeholder="Tìm tên khách hàng..." value={search} onChange={e => setSearch(e.target.value)} style={{ marginBottom: 8 }} />
          <select name="customerId" defaultValue={task?.customer?.id || ''}>
            <option value="">Chưa chọn</option>
            {task?.customer && <option value={task.customer.id}>{task.customer.name}</option>}
            {customers.data?.items.filter(c => c.id !== task?.customer?.id).map(c => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </label>
        <label>
          Ghi chú
          <textarea name="note" defaultValue={task?.note} />
        </label>
        <div className="form-grid">
          <label>
            Hạn chót
            <input name="dueDate" type="date" defaultValue={task?.dueDate?.slice(0, 10) || ''} />
          </label>
          <label>
            Độ ưu tiên
            <select name="priority" defaultValue={task?.priority || 'NORMAL'}>
              <option value="LOW">Thấp</option>
              <option value="NORMAL">Bình thường</option>
              <option value="HIGH">Cao</option>
              <option value="URGENT">Khẩn cấp</option>
            </select>
          </label>
        </div>
        <div className="form-grid">
          <label>
            Kênh liên hệ
            <select name="contactChannel" defaultValue={task?.contactChannel || ''}>
              <option value="">Không có</option>
              <option value="phone">Gọi điện</option>
              <option value="zalo">Zalo</option>
              <option value="visit">Gặp trực tiếp</option>
            </select>
          </label>
          {task && (
            <label>
              Trạng thái
              <select name="status" defaultValue={task.status}>
                <option value="TODO">Cần làm</option>
                <option value="IN_PROGRESS">Đang làm</option>
                <option value="DONE">Hoàn thành</option>
                <option value="CANCELLED">Đã hủy</option>
              </select>
            </label>
          )}
        </div>
      </Form>
    </Modal>
  );
}
