server {
    listen 80;
    listen [::]:80;
    server_name sakura.ldhuy.name.vn;
    location ^~ /.well-known/acme-challenge/ {
        root /srv/sakura/acme;
    }
    location / { return 301 https://sakura.ldhuy.name.vn$request_uri; }
}
