-- CreateEnum: TaskPriority
CREATE TYPE "TaskPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

-- CreateEnum: TaskStatus
CREATE TYPE "TaskStatus" AS ENUM ('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED');

-- CreateTable: SalesTask
CREATE TABLE "SalesTask" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" UUID NOT NULL,
    "customerId" UUID,
    "title" TEXT NOT NULL,
    "note" TEXT NOT NULL DEFAULT '',
    "dueDate" TIMESTAMP(3),
    "priority" "TaskPriority" NOT NULL DEFAULT 'NORMAL',
    "status" "TaskStatus" NOT NULL DEFAULT 'TODO',
    "contactChannel" TEXT NOT NULL DEFAULT '',
    "completedAt" TIMESTAMP(3),
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "SalesTask_pkey" PRIMARY KEY ("id")
);

-- AlterTable: Customer – add CRM pipeline fields
ALTER TABLE "Customer" ADD COLUMN "expectedRevenue" DECIMAL(15,0);
ALTER TABLE "Customer" ADD COLUMN "nextContactDate" TIMESTAMP(3);
ALTER TABLE "Customer" ADD COLUMN "lastContactDate" TIMESTAMP(3);
ALTER TABLE "Customer" ADD COLUMN "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- CreateIndex
CREATE INDEX "SalesTask_userId_status_dueDate_idx" ON "SalesTask"("userId", "status", "dueDate");
CREATE INDEX "SalesTask_userId_customerId_idx" ON "SalesTask"("userId", "customerId");
CREATE INDEX "SalesTask_dueDate_status_idx" ON "SalesTask"("dueDate", "status");

-- AddForeignKey
ALTER TABLE "SalesTask" ADD CONSTRAINT "SalesTask_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SalesTask" ADD CONSTRAINT "SalesTask_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
